# 应用系统设置
[setting]
    logpath = "log/"
    JwtSecret = "123456789"
    PageSize = 2

# 数据库连接
[database]
    host = "192.168.100.50:4000"
    user = "root"
    pass = "123456"
    name = "coypus"
    type = "mysql"
    TablePrefix = "go_"
